[package]
name = "RayTracing"
version = "0.1.0"
authors = ["Tiqur"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.0"
rand = "0.7.3"
console = "0.11.2"

[profile.dev]
opt-level = 3